services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
  ollama:
    image: ollama/ollama:0.32.2
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    entrypoint: ["/bin/sh", "/ollama-entrypoint.sh"]
volumes:
  ollama_data: